# Example Docker Compose for Docker Lab

dockerlab-www:
  build: dockerlab-www
  container_name: dockerlab-www
  privileged: true
  links:
  - dockerlab-db
  env_file: 
  - passwords.env

# dockerlab-lab:
#   build: dockerlab-lab
#   container_name: dockerlab-lab
#   privileged: true

dockerlab-dns:
  build: dockerlab-dns
  container_name: dockerlab-dns
  ports:
  - "53:53/udp"
  env_file:
  - passwords.env

dockerlab-db:
  image: postgres:9.3
  container_name: dockerlab-db
  restart: always
  env_file: 
  - passwords.env
  volumes_from:
  - dockerlab-db-data

dockerlab-db-data:
  image: busybox
  container_name: dockerlab-db-data
  volumes:
   - "/etc/postgresql"
   - "/var/log/postgresql"
   - "/var/lib/postgresql/data"